version: "3.9"
services:
  webserver:
    ports:
      - "80:80"
    build: .
    volumes:
      - ./src:/var/www/html
  database:
    ports:
      - "3306:3306"
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - dbData:/var/lib/database
volumes:
  app:
  dbData: